### ISSUE TITLE
Unhandled exception while retrieving value of "fan_id"

### ISSUE THREAD

**Issue by orontee** [impliedchaos/mopidy-bandcamp#19]
Mopidy-Bandcamp extension stopped working few weeks ago. 

Here is an extract of the mopidy service journal:
```
nov. 10 11:43:52 argos mopidy[482]: ERROR    [BandcampBackend-4] mopidy_bandcamp Failed to get collection
nov. 10 11:43:52 argos mopidy[482]: Traceback (most recent call last):
nov. 10 11:43:52 argos mopidy[482]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_bandcamp/library.py", line 46, in browse
nov. 10 11:43:52 argos mopidy[482]:     data = self.backend.bandcamp.get_collection(
nov. 10 11:43:52 argos mopidy[482]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_bandcamp/bandcamp.py", line 136, in get_collection
nov. 10 11:43:52 argos mopidy[482]:     self.fan_id = resp.json()["fan_id"]
nov. 10 11:43:52 argos mopidy[482]: KeyError: 'fan_id'
```

Installed version:
```
matthias@argos:~ $ python3 -m pip show mopidy mopidy-bandcamp
Name: Mopidy
Version: 3.4.2
Summary: Mopidy is an extensible music server written in Python
Home-page: https://mopidy.com/
Author: Stein Magnus Jodal
Author-email: stein.magnus@jodal.no
License: Apache License, Version 2.0
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: Mopidy-Local, Mopidy-Listenbrainz, Mopidy-Iris, Mopidy-InternetArchive, Mopidy-Bandcamp
---
Name: Mopidy-Bandcamp
Version: 1.1.5
Summary: Backend for listening to bandcamp
Home-page: https://github.com/impliedchaos/mopidy-bandcamp
Author: Dave Maez
Author-email: impliedchaos@gmail.com
License: MIT License
Location: /usr/local/lib/python3.9/dist-packages
Requires: Pykka, setuptools, Mopidy
Required-by: 
```

**Comment by orontee** [comment]
Problem fixed after I updated the identity token in my configuration file. Feel free to close this issue.

May be the exception could be catch and a proper message logged to improve user experience?

Whatever, thank you very much for providing this nice extension.
